### PR TITLE
Typo as in fileattachment in PDFWindow.cpp

### PR DESCRIPTION
**Pull request by Naba7**
I corrected the typo in fileattachment by entering a space in between.

### CODE REVIEW

**Comment by humdingerb** [comment]
Thanks Nabanita.
Thing is, if you change the string for ADD_FILEATTACHMENT_ANNOT_CMD in PDFWindow.cpp we'll need to re-generate the en.catkeys. Which will in turn results all the other *.catkeys needing slight changes, including your new hi.catkeys.

I suggest to remove your hi.catkeys from this PR again for now.
Generate the new en.catkeys with "make catkeys" and include that in this PR.

I will then upload the new en.catkeys to Polyglot (and manually add the missing space in all the other translations and upload those as well, to save the translators some work).

If you want to, you can then export all catkeys from Polyglot and create another PR for that. Including adding all new languages in the Makefile.

Please don't hesitate to ask, if I was unclear about something. :)

**Comment by Naba7** [comment]
okay I am sorry .I was stuck with my exams.I will resolve this now. I get you completely.

**Comment by Naba7** [comment]
I am trying to make new en.catkeys but I am unable to. The previous en.catkeys file is intact though.
I have checked this out https://www.haiku-os.org/community/getting-involved/translating/ still unable to generate.

**Comment by Naba7** [comment]
Here is the en.catkeys file
[en.zip](https://github.com/HaikuArchives/BePDF/files/3071224/en.zip)

**Comment by humdingerb** [comment]
It looks like you just edited the "Add file attachment annotation" string in the en.catkeys. This doesn't work, because the "fingerprint" (the hash in the first line of the catkeys file) doesn't match. Whenever a string changes, you'll have to re-generate the en.catkeys file with "make catkeys" after building BePDF.

You wanna do that and add it to this PR?

**Comment by Naba7** [comment]
I tried but I couldn't re-generate using "make catkeys" Can you give me the detailed instruction to do it? I will do it.

**Comment by humdingerb** [comment]
Just locate the Makefile for the app and from its directory do a "make catkeys". This will generate the en.catkeys in the "locales" folder there.

**Comment by Naba7** [comment]
How to include Catalog.h to source code? I can't open the directory to source code

**Comment by humdingerb** [comment]
Why not simply clone the BePDF github under Haiku?

In any case, as BePDF is alredy completely localized, you don't have to add the Catalog.h header anywhere. You'll never have to edit Catalog.h, it's a system header.

**Comment by Naba7** [comment]
Okay! Well in the localisation of GUI applications of haiku docs it was
written,so I thought it might be necessary.

**Comment by humdingerb** [comment]
Yeah, all [that](https://www.haiku-os.org/community/getting-involved/translating/3rdparty/) is still correct, but already done for BePDF. :)

**Comment by Naba7** [comment]
[en_catkeys.pdf](https://github.com/HaikuArchives/BePDF/files/3103193/en_catkeys.pdf)

Is it the correct file?

**Comment by humdingerb** [comment]
Yes, this is the old en.catkeys file (with a wrong .pdf suffix).

**Comment by Naba7** [comment]
Actually I GitHub doesn't support sending en.catkeys format,so I sent it in
a .pdf

**Comment by humdingerb** [comment]
@Naba7, do you still want to work on getting the catkeys uptodate, or would you prefer someone else taking care of that?

**Comment by Naba7** [comment]
No. I think someone else should take care of it. Infact I had a pr.

**Comment by humdingerb** [comment]
Alright. Thanks for the quick reply.

**Pull request merged**
