### PR TITLE
Add simplified Chinese translation

### PR DESCRIPTION
**Pull request by gzdxyy**
Add simplified Chinese translation

### CODE REVIEW

**Comment by humdingerb** [comment]
Translations are done at [Polyglot](https://i18n.kacperkasper.pl/projects/7). Can you register there and upload your catkeys? That would ensure you're being credited correctly, as Polyglot keeps track of that.

**Comment by gzdxyy** [comment]
Thank you. I'll try

**Comment by humdingerb** [comment]
I gave you permissions for Chinese at Polyglot. If you experience any problems, let me know.

**Comment by gzdxyy** [comment]
> I gave you permissions for Chinese at Polyglot. If you experience any problems, let me know.

OK, I have successfully joined, Thank you.

**Comment by humdingerb** [comment]
Very good! Translations will be updated before the next release.
Feel free to translate other apps at Polyglot. :)

**Pull request closed without merging**
