### PR TITLE
Changed opening page (Start.pdf)

### PR DESCRIPTION
**Pull request by humdingerb**
I've disliked BePDFs start page for over a decade now...

Start.wbi is a WonderBrush image, but the actual pdf was created from
Start.svg in Inkscape, because Haiku's pdf export doesn't work very
well yet.
The font is Baskerville BT.

A preview of the PDF: https://0x0.st/H_y.pdf

### CODE REVIEW

**Comment by waddlesplash** [comment]
Would it be possible to preserve the original title font ("New Century Schoolbook")? Other than that, very nice!

**Comment by waddlesplash** [comment]
Also, maybe change the "Welcome to the premier PDF reader for Haiku" to just "The premier PDF reader for Haiku".

**Comment by humdingerb** [comment]
It looks like the "New Century Schoolbook" is only commercially available. Don't know about the Baskerville, but that's one I have here...   
Agree on the text change.

**Comment by waddlesplash** [comment]
Can you "steal" the text from the old PDF then? Or I might be able to dump the paths...

**Comment by humdingerb** [comment]
I wouldn't know how. Also there's the new text also...  
Also, the old font doesn't strike me as especially worthy to preserve.

**Comment by waddlesplash** [comment]
I suppose so.

**Pull request merged**
