### PR TITLE
Convert some of BePDF to use the new Haiku Layout API

### PR DESCRIPTION
**Pull request by TwoFX**
I will completely rewrite the history once I'm done with everything. Currently working on getting rid of libsanta, after that some cleanup.

### CODE REVIEW

**Comment by waddlesplash** [comment]
Don't squash all your commits into one; one commit per dialog/control is better.

**Comment by waddlesplash** [comment]
Everything you have so far looks OK.

**Comment by TwoFX** [comment]
Alright, I am pretty much done for now. The reason why I did not end up tackling the ColumnListViews and libsanta is that I cannot properly test my changes because of a bug which I filed as #26. I did not investigate how hard it is to fix due to a lack of time, but I guess this could be looked into as part of another task to continue the layouting work on BePDF.

**Comment by waddlesplash** [comment]
Thanks!

**Pull request merged**
